# Generated by Django 5.2.4 on 2025-07-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidom',
            new_name='apellidoM',
        ),
    ]
