# Generated by Django 5.2.4 on 2025-07-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='categoria',
            field=models.CharField(choices=[('personal', 'Personal'), ('trabajo', 'Trabajo'), ('estudio', 'Estudio'), ('ocio', 'Ocio'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
