# Generated by Django 5.2.4 on 2025-07-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
